# run: conda env create -f environment.yml
name: animateanyone
channels:
  - pytorch
  - nvidia
dependencies:
  - python=3.8.5
  - pip
  - pytorch=2.4.1
  - torchvision=0.13.1
  - pytorch-cuda=12.1
  - numpy=1.19.2
  - pip:
    - transformers==4.19.2
    - diffusers
    - invisible-watermark
    - albumentations==0.4.3
    - opencv-python==4.1.2.30
    - pudb==2019.2
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - pytorch-lightning
    - omegaconf==2.1.1
    - test-tube>=0.7.5
    - streamlit>=0.73.1
    - einops==0.3.0
    - torch-fidelity==0.3.0
    - kornia==0.6
    - open_clip_torch==2.0.2
    - wandb
